# Generated by Django 5.2.4 on 2025-09-15 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('available', models.BooleanField(default=True)),
                ('wait_time_low', models.PositiveIntegerField(default=0, help_text='Waiting time in minutes')),
                ('wait_time_high', models.PositiveIntegerField(default=0, help_text='Maximum waiting time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='authentication.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'ordering': ['name'],
            },
        ),
    ]
